engines:
  duplication:
      enabled: true
      config:
        languages:
        - javascript:
  eslint:
      enabled: true
  fixme:
      enabled: true
  nodesecurity:
      enabled: true
  markdownlint:
      enabled: true
ratings:
  paths:
  - src/**
  - e2e/**
exclude_paths:
  - dist
  - doc
  - node_modules
  - .git
  - .idea
  - CHANGELOG.md
  - LICENSE.md
  - "**.d.ts"
  - "**.js"
  - "**.json"