language: node_js
node_js: 'node'
install: npm install
before_script:
  - npm run lint
  - npm run test
  - npm run e2e
script:
  - npm run build:prod
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 2a8d422555c5db5d65fce402037fe26970fa521cd3614449c0337d1b4a1b7fad
branches:
  only:
    - master
